### ISSUE TITLE
mutable default <class 'pydantic.types.SecretStr'> for field api_key is not allowed: use default_factory

### ISSUE THREAD

**Issue by andrew-candela** [peopledatalabs/peopledatalabs-python#25]
**Describe the bug**
Pydantic complains that you're supplying a mutable type as the default value for a field in the `PDLPY.api_key`.

**To Reproduce**
Try to import the module: `from peopledatalabs import PDLPY`

**Expected behavior**
You should be able to import the module

**Screenshots**
N/A

 - peopledatalabs Library Version: 1.1.2
 - Python Version: 3.11.2

**Additional context**
Here's my stacktrace:

```
Traceback (most recent call last):
  File "/Users/me/Documents/workspace/pdl_api_test/src/main.py", line 11, in <module>
    from src.lib.pdl_api import PDLCLient
  File "/Users/me/Documents/workspace/pdl_api_test/src/lib/pdl_api.py", line 15, in <module>
    from peopledatalabs import PDLPY  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/src-3ck7Pn5u-py3.11/lib/python3.11/site-packages/peopledatalabs/__init__.py", line 6, in <module>
    from .main import PDLPY
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/src-3ck7Pn5u-py3.11/lib/python3.11/site-packages/peopledatalabs/main.py", line 30, in <module>
    @dataclass
     ^^^^^^^^^
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/src-3ck7Pn5u-py3.11/lib/python3.11/site-packages/pydantic/dataclasses.py", line 265, in dataclass
    return wrap(_cls)
           ^^^^^^^^^^
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/src-3ck7Pn5u-py3.11/lib/python3.11/site-packages/pydantic/dataclasses.py", line 260, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/src-3ck7Pn5u-py3.11/lib/python3.11/site-packages/pydantic/dataclasses.py", line 159, in _process_class
    cls: Type['Dataclass'] = dataclasses.dataclass(  # type: ignore
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'pydantic.types.SecretStr'> for field api_key is not allowed: use default_factory
```

**Comment by andrew-candela** [comment]
Like the Pydantic message suggests, you can supply the default `SecretStr` with a default_factory to resolve this.
